---
# vars file for nessi project

# Automatically configure NESSI CVMFS repos.
eessi_cvmfs_repos_enabled: true

# Email address for the project.
eessi_email: thomas.roblitz@uib.no

#
# Defaults for nessi.no repos.
#

# We do not use a config repo anymore.
eessi_cvmfs_config_repo: {}

# Public keys for the repositories, which you can find on the Stratum 0 at:
# /etc/cvmfs/keys/*.pub
# Note: you first have to run the stratum0.yml playbook once to generate the repositories and keys.
eessi_cvmfs_keys:
  - path: /etc/cvmfs/keys/nessi.no/pilot.nessi.no.pub
    key: |
     -----BEGIN PUBLIC KEY-----
     MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2fCoxTEM5bJoOv6/JYl3
     FuzcA5J0Dj6MTE2ltaNqpWNnscaPUZVNiXkPgUSepxx6Om12i6b7lHW2q7Vs3ua0
     X+CWqccAQ1VUIh/bI33YG+6KsIYHJhDgU653aqodVo5O2Ei+DOZqwin9MQZ1+XDz
     Vvfh3nEOq+z8XROIbXeBBzGgjSiXt+RWUh8WzKmaJamekPPFJQTkAO7XiSzlK9l7
     OVRmsO0cswKIr0qoTk34o/JOMq75uxsqartoERw6Qw5qGxbTs7NduFTW/FaZgEiQ
     UT5djm4zu+fCkivsIZOil4hfvCTVdcCq3z8L3UOhLLE2IbkPzebNo+a65DRDe+zf
     7wIDAQAB
     -----END PUBLIC KEY-----

# URLs for all the Stratum 1 servers.
eessi_cvmfs_server_urls:
  - domain: nessi.no
    use_geoapi: true
    urls:
      - "http://stratum1-a.nessi.no/cvmfs/@fqrn@"
      - "http://stratum1-b.nessi.no/cvmfs/@fqrn@"

# Configuration of all the repositories.
eessi_cvmfs_repositories:
  - repository: pilot.nessi.no
    stratum0: stratum0.nessi.no
    owner: "{{ cvmfs_repo_owner | default('root') }}"
    key_dir: /etc/cvmfs/keys/nessi.no
    server_options:
      - CVMFS_AUTO_GC=false
      - CVMFS_AUTO_TAG_TIMESPAN="30 days ago"
      - CVMFS_GARBAGE_COLLECTION=true
    client_options: []
    use_for_ci: false
    description: "Repository that contains the NESSI software stack."

# Meta information for CVMFS Stratum servers
cvmfs_server_meta_administrator: "NESSI CVMFS Administrators"
cvmfs_server_meta_email: "{{ eessi_email }}"
cvmfs_server_meta_organisation: "NESSI"
cvmfs_server_meta_custom:
  _comment: "See https://documentation.sigma2.no/index.html"
cvmfs_server_meta_website: "https://documentation.sigma2.no/index.html"

# Override all the Galaxy defaults by our NESSI defaults.
# This is required, beucase the galaxy_* variables are used inside the Ansible tasks.
galaxy_cvmfs_config_repo: "{{ eessi_cvmfs_config_repo }}"
galaxy_cvmfs_keys: "{{ eessi_cvmfs_keys }}"
galaxy_cvmfs_server_urls: "{{ eessi_cvmfs_server_urls }}"
galaxy_cvmfs_repositories: "{{ eessi_cvmfs_repositories }}"
galaxy_cvmfs_repos_enabled: "{{ eessi_cvmfs_repos_enabled }}"
